### ISSUE TITLE
no space on device

### ISSUE THREAD

**Issue by gbishop** [parente/mostly-tmpnb#2]
When I try the local deploy I get errors in the `make images` step.

```
8a0bc36f08cd: Error pulling image (latest) from docker.io/jupyter/minimal-notebook, Untar re-exec error: exit status 1: output: write /usr/share/locale/vi/LC_MESSAGES/git.mo: no space left on device LC_MESSAGES/git.mo: no space left on device
```

No lack of disk space on my system. Perhaps the created VM is limited?

**Comment by parente** [comment]
Fixed in 85c0f23. virtualbox.makefile was missing exports on the target variables. They are now added to the recipe shell environment properly.
